In [5]:
import string
import random

def generate_substitution_key():
    # Generates a random substitution key by shuffling the alphabet
    alphabet = list(string.ascii_lowercase)
    shuffled_alphabet = alphabet[:]
    random.shuffle(shuffled_alphabet)
    return dict(zip(alphabet, shuffled_alphabet))

def encrypt(plaintext, key):
    ciphertext = ""
    for char in plaintext:
        if char.isalpha():
            # Preserve the case of the letter
            is_upper = char.isupper()
            # Get the corresponding encrypted character from the key
            encrypted_char = key[char.lower()]
            # Convert back to uppercase if necessary
            if is_upper:
                encrypted_char = encrypted_char.upper()
            ciphertext += encrypted_char
        else:
            ciphertext += char  # Non-alphabetic characters are added unchanged
    return ciphertext

def decrypt(ciphertext, key):
    reversed_key = {v: k for k, v in key.items()}
    plaintext = ""
    for char in ciphertext:
        if char.isalpha():
            # Preserve the case of the letter
            is_upper = char.isupper()
            # Get the corresponding decrypted character
            decrypted_char = reversed_key[char.lower()]
            # Convert back to uppercase if necessary
            if is_upper:
                decrypted_char = decrypted_char.upper()
            plaintext += decrypted_char
        else:
            plaintext += char  # Non-alphabetic characters are added unchanged
    return plaintext

# Generate a substitution key
substitution_key = generate_substitution_key()
print("Substitution Key:", substitution_key)

# Example usage
plaintext = input("Enter the plain text: ")

ciphertext = encrypt(plaintext, substitution_key)
print("Plaintext:", plaintext)
print("Ciphertext:", ciphertext)

# Decrypt the ciphertext back to plaintext
decrypted_text = decrypt(ciphertext, substitution_key)
print("Decrypted Text:", decrypted_text)

Substitution Key: {'a': 'c', 'b': 'e', 'c': 'j', 'd': 'u', 'e': 'o', 'f': 'l', 'g': 's', 'h': 'h', 'i': 'w', 'j': 'z', 'k': 't', 'l': 'm', 'm': 'q', 'n': 'p', 'o': 'a', 'p': 'r', 'q': 'f', 'r': 'k', 's': 'd', 't': 'y', 'u': 'i', 'v': 'n', 'w': 'v', 'x': 'x', 'y': 'g', 'z': 'b'}
Enter the plain text: Reva
Plaintext: Reva
Ciphertext: Konc
Decrypted Text: Reva


In [8]:
import numpy as np

keyMatrix = [[0] * 3 for _ in range(3)]
messageVector = [[0] for _ in range(3)]
cipherMatrix = [[0] for _ in range(3)]

def getKeyMatrix(key):
    k = 0
    for i in range(3):
        for j in range(3):
            keyMatrix[i][j] = ord(key[k]) - 65  # Convert to range 0-25
            k += 1

def mod_inverse(a, m):
    """Compute the modular inverse of a modulo m."""
    a = a % m
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    raise ValueError(f"No modular inverse for {a} modulo {m}")



Key Matrix:
[17, 21, 2]
[17, 18, 2]
[5, 21, 19]
Message Matrix:
[12]
[14]
[17]
Cipher Matrix:
[12]
[22]
[1]
Ciphertext: MWB
Inverse matrix modulo 26:
[[ 4 15 24]
 [ 9 17  0]
 [15  6 17]]
Decrypted Matrix:
[12]
[14]
[17]
Decrypted Text: MOR
